pipeline {
  agent any
  environment {
    DB_PASSWORD = credentials('db_password')
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Run Ansible') {
      steps {
        sh '''
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i ansible/inventory.ini ansible/db.yml \
            --limit db \
            -e db_password=$DB_PASSWORD
        '''
      }
    }
  }
}